var charactersData = {
	group1: [
		{ name: 'Роджер', image: 'roger/1.jpg', link: 'characters/roger/index.html' },
		{ name: 'Шанкс', image: 'shansk/1.jpg', link: 'shansk/index.html' },
		{ name: 'Бекман', image: 'beckman/1.jpg', link: 'beckman/index.html' },
		{ name: 'Лаки', image: 'laki/1.jpg', link: 'laki/index.html' },
		{ name: 'Ясопп', image: 'yassop/1.jpg', link: 'yassop/index.html' },
		{ name: 'Макино', image: 'makino/1.jpg', link: 'makino/index.html' },
		{ name: 'Вул', image: 'vul/1.jpg', link: 'vul/index.html' },
		{ name: 'Хигума', image: 'higuma/1.jpg', link: 'higuma/index.html' },
		{ name: 'Коби', image: 'kobi/1.jpg', link: 'kobi/index.html' },
		{ name: 'Альвида', image: 'alvida/1.jpg', link: 'alvida/index.html' },
		{ name: 'Хельмеппо', image: 'helmeppo/1.jpg', link: 'helmeppo/index.html' },
		{ name: 'Moрган', image: 'morgan/1.jpg', link: 'morgan/index.html' },
		{ name: 'Коширо', image: 'koshiro/1.jpg', link: 'koshiro/index.html' },
		{ name: 'Куина', image: 'kuina/1.jpg', link: 'kuina/index.html' },
		{ name: 'Домо-кун', image: 'domo-kun/1.jpg', link: 'domo-kun/index.html' },
		{ name: 'Кабаджи', image: 'kabadji/1.jpg', link: 'kabadji/index.html' },
		{ name: 'Багги', image: 'buggy/1.jpg', link: 'buggy/index.html' },
		{ name: 'Ричи', image: 'richi/1.jpg', link: 'richi/index.html' },
		{ name: 'Моджи', image: 'modji/1.jpg', link: 'modji/index.html' },
		{ name: 'Будл', image: 'budl/1.jpg', link: 'budl/index.html' },
		{ name: 'Шушу', image: 'shushu/1.jpg', link: 'shushu/index.html' },
		{ name: 'Рейли', image: 'rayleigh/1.jpg', link: 'rayleigh/index.html' },
		{ name: 'Гаймон', image: 'gaimon/1.jpg', link: 'gaimon/index.html' },
		{ name: 'Куро', image: 'kuro/1.jpg', link: 'kuro/index.html' },
		{ name: 'Кая', image: 'kaya/1.jpg', link: 'kaya/index.html' },
		{ name: 'Пииман', image: 'piiman/1.jpg', link: 'piiman/index.html' },
		{ name: 'Таманеги', image: 'tamanegi/1.jpg', link: 'tamanegi/index.html' },
		{ name: 'Нинжин', image: 'ninjin/1.jpg', link: 'ninjin/index.html' },
		{ name: 'Усопп', image: 'usopp/1.jpg', link: 'usopp/index.html' },
		{ name: 'Мерри', image: 'merry/1.jpg', link: 'merry/index.html' },
		{ name: 'Джанго', image: 'django/1.jpg', link: 'django/index.html' },
		{ name: 'Бучи', image: 'buchi/1.jpg', link: 'buchi/index.html' },
		{ name: 'Сям', image: 'Sham/1.jpg', link: 'Sham/index.html' },
		{ name: 'Банкина', image: 'Bankina/1.jpg', link: 'Bankina/index.html' },
		{ name: 'Ёсаку', image: 'Yesaku/1.jpg', link: 'Yesaku/index.html' },
		{ name: 'Джонни', image: 'Johnny1.jpg', link: 'Johnny/index.html' },
		{ name: 'Зефф', image: 'Zeff/1.jpg', link: 'Zeff/index.html' },
		{ name: 'Фулботи', image: 'Fullbody/1.jpg', link: 'Fullbody/index.html' },
		{ name: 'Патти', image: 'Patty/1.jpg', link: 'Patty/index.html' },
		{ name: 'Гин', image: 'Gin/1.jpg', link: 'Gin/index.html' },
		{ name: 'Пандамен', image: 'Pandaman/1.jpg', link: 'Pandaman/index.html' },
		{ name: 'Криг', image: 'Krieg/1.jpg', link: 'Krieg/index.html' },
		{ name: 'Михоук', image: 'Mihawk/1.jpg', link: 'Mihawk/index.html' },
		{ name: 'Перл', image: 'Pearl/1.jpg', link: 'Pearl/index.html' },
		{ name: 'Чу', image: 'Chu/1.jpg', link: 'Chu/index.html' },
		{ name: 'Нэдзуми', image: 'Nezumi/1.jpg', link: 'Nezumi/index.html' },
		{ name: 'Хатчан', image: 'Hatchan/1.jpg', link: 'Hatchan/index.html' },
		{ name: 'Курооби', image: 'Kuroobi/1.jpg', link: 'Kuroobi/index.html' },
		{ name: 'Арлонг', image: 'Arlong/1.jpg', link: 'Arlong/index.html' },
		{ name: 'Ноджика', image: 'Nojiko/1.jpg', link: 'Nojiko/index.html' },
		{ name: 'Ганзо', image: 'Ganzo/1.jpg', link: 'Ganzo/index.html' },
		{ name: 'Мому', image: 'Momu/1.jpg', link: 'Momu/index.html' },
		{ name: 'Белл-мера', image: 'Bellmera/1.jpg', link: 'Bellmera/index.html' },
		{ name: 'Нако', image: 'Naco/1.jpg', link: 'Naco/index.html' },
		{ name: 'Богарт', image: 'Bogart/1.jpg', link: 'Bogart/index.html' },
		{ name: 'Гарп', image: 'Garp/1.jpg', link: 'Garp/index.html' },
		{ name: 'Ташиги', image: 'Tashigi/1.jpg', link: 'Tashigi/index.html' },
		{ name: 'Иппон-Мацу', image: 'Matsu/1.jpg', link: 'Matsu/index.html' },
		{ name: 'Смокер', image: 'Smoker/1.jpg', link: 'Smoker/index.html' },
		{ name: 'Драгон', image: 'Dragon/1.jpg', link: 'Dragon/index.html' },
		{ name: 'Крокус', image: 'Crocus/1.jpg', link: 'Crocus/index.html' },
		{ name: 'Лабун', image: 'Laboon/1.jpg', link: 'Laboon/index.html' },
		{ name: 'Мистер 9', image: 'Mr.9/1.jpg', link: 'Mr.9/index.html' },
		{ name: 'Виви', image: 'Vivi/1.jpg', link: 'Vivi/index.html' },
		{ name: 'Фарайдей', image: 'Faraday/1.jpg', link: 'Faraday/index.html' },
		{ name: 'Мистер 13', image: 'Mr.13/1.jpg', link: 'Mr.13/index.html' },
		{ name: 'Игарам', image: 'Igaram/1.jpg', link: 'Igaram/index.html' },
		{ name: 'Мандей', image: 'Manday/1.jpg', link: 'Manday/index.html' },
		{ name: 'Симиджу', image: 'Shimizu/1.jpg', link: 'Shimizu/index.html' },
		{ name: 'Кару', image: 'Karu/1.jpg', link: 'Karu/index.html' },
		{ name: 'Мистер 5', image: 'Mr.5/1.jpg', link: 'Mr.5/index.html' },
		{ name: 'Валентайн', image: 'Valentine/1.jpg', link: 'Valentine/index.html' },
		{ name: 'Дорри', image: 'Dorrie/1.jpg', link: 'Dorrie/index.html' },
		{ name: 'Броги', image: 'Brogie/1.jpg', link: 'Brogie/index.html' },
		{ name: 'Голдевник', image: 'Goldenwick/1.jpg', link: 'Goldenwick/index.html' },
		{ name: 'Галдино', image: 'Goldino/1.jpg', link: 'Goldino/index.html' },
		{ name: 'Крокодайл', image: 'Crocodile/1.jpg', link: 'Crocodile/index.html' },
		{ name: 'Бонтян', image: 'Bontian/1.jpg', link: 'Bontian/index.html' },
		{ name: 'Вапол', image: 'Vapol/1.jpg', link: 'Vapol/index.html' },
		{ name: 'Чесс', image: 'Chess/1.jpg', link: 'Chess/index.html' },
		{ name: 'Куромаримо', image: 'Kuromarimo/1.jpg', link: 'Kuromarimo/index.html' },
		{ name: 'Далтон', image: 'Dalton/1.jpg', link: 'Dalton/index.html' },
		{ name: 'Куреха', image: 'Kureha/1.jpg', link: 'Kureha/index.html' },
		{ name: 'Робсон', image: 'Robson/1.jpg', link: 'Robson/index.html' },
		{ name: 'Хилюлюк', image: 'Hiluluk/1.jpg', link: 'Hiluluk/index.html' },
		{ name: 'Кобра', image: 'Cobra/1.jpg', link: 'Cobra/index.html' },
		{ name: 'Эйс', image: 'Ace/1.jpg', link: 'Ace/index.html' },
		{ name: 'Пелл', image: 'Pell/1.jpg', link: 'Pell/index.html' },
		{ name: 'Чака', image: 'Chaka/1.jpg', link: 'Chaka/index.html' },
		{ name: 'Даблфингер', image: 'Doublefinger/1.jpg', link: 'Doublefinger/index.html' },
		{ name: 'Кристмас', image: 'Christmas/1.jpg', link: 'Christmas/index.html' },
		{ name: 'Лассу', image: 'Lassu/1.jpg', link: 'Lassu/index.html' },
		{ name: 'Мистер 4', image: 'Mr.4/1.jpg', link: 'Mr.4/index.html' },
		{ name: 'Бонс', image: 'Bons/1.jpg', link: 'Bons/index.html' },
		{ name: 'Мацуге', image: 'Matsuge/1.jpg', link: 'Matsuge/index.html' },
		{ name: 'Коза', image: 'Koza/1.jpg', link: 'Koza/index.html' },
		{ name: 'Тото', image: 'Toto/1.jpg', link: 'Toto/index.html' },
		{ name: 'Хина', image: 'Hina/1.jpg', link: 'Hina/index.html' },
		{ name: 'Хасами', image: 'Hasami/1.jpg', link: 'Hasami/index.html' },
		{ name: 'Кейми', image: 'Keimi/1.jpg', link: 'Keimi/index.html' },
		{ name: 'Паппг', image: 'Pappag/1.jpg', link: 'Pappagcharacter//index.html' },
	],
	group2: [
		{ name: 'Октопако', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фазерсдей', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мистер 7', image: '/1.jpg', link: '/index.html' },
		{ name: 'Терракотта', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тити', image: '/1.jpg', link: '/index.html' },
		{ name: 'Маширо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Саркис', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бёрджесс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Огер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Беллами', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кью', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лили', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тич', image: '/1.jpg', link: '/index.html' },
		{ name: 'Стронгер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Седзе', image: '/1.jpg', link: '/index.html' },
		{ name: 'Крикет', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дофламинго', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кума', image: '/1.jpg', link: '/index.html' },
		{ name: 'Цуру', image: '/1.jpg', link: '/index.html' },
		{ name: 'Джоз', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лаффит', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сэнгоку', image: '/1.jpg', link: '/index.html' },
		{ name: 'Белоус', image: '/1.jpg', link: '/index.html' },
		{ name: 'Марко', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ганфолл', image: '/1.jpg', link: '/index.html' },
		{ name: 'Вайпер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пьерр', image: '/1.jpg', link: '/index.html' },
		{ name: 'Су', image: '/1.jpg', link: '/index.html' },
		{ name: 'Конис', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пагая', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гедацу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сатори', image: '/1.jpg', link: '/index.html' },
		{ name: 'Холи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шира', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фуза', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ом', image: '/1.jpg', link: '/index.html' },
		{ name: 'Брахам', image: '/1.jpg', link: '/index.html' },
		{ name: 'Айса', image: '/1.jpg', link: '/index.html' },
		{ name: 'Камакири', image: '/1.jpg', link: '/index.html' },
		{ name: 'Яма', image: '/1.jpg', link: '/index.html' },
		{ name: 'Энель', image: '/1.jpg', link: '/index.html' },
		{ name: 'Нола', image: '/1.jpg', link: '/index.html' },
		{ name: 'Калгара', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ноланд', image: '/1.jpg', link: '/index.html' },
		{ name: 'Касигами', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кудзан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шелли', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тонджит', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фокси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Порча', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гамбург', image: '/1.jpg', link: '/index.html' },
		{ name: 'Итомимиджу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Капоти', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кибагаэру', image: '/1.jpg', link: '/index.html' },
		{ name: 'Монда', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тютюн', image: '/1.jpg', link: '/index.html' },
		{ name: 'Биг Пан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пиклз', image: '/1.jpg', link: '/index.html' },
		{ name: 'Чимни', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кокоро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гомбэ', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хаттори', image: '/1.jpg', link: '/index.html' },
		{ name: 'Паули', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лулу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тайлстоун', image: '/1.jpg', link: '/index.html' },
		{ name: 'Калифа', image: '/1.jpg', link: '/index.html' },
		{ name: 'Айсберг', image: '/1.jpg', link: '/index.html' },
		{ name: 'Каку', image: '/1.jpg', link: '/index.html' },
		{ name: 'Замбай', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бруно', image: '/1.jpg', link: '/index.html' },
		{ name: 'Луччи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Моджи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Френки', image: '/1.jpg', link: '/index.html' },
		{ name: 'Киви', image: '/1.jpg', link: '/index.html' },
		{ name: 'Том', image: '/1.jpg', link: '/index.html' },
		{ name: 'Жоржи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Спандам', image: '/1.jpg', link: '/index.html' },
		{ name: 'Стиви', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бушон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тю Бон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фанкфрид', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гоморра', image: '/1.jpg', link: '/index.html' },
		{ name: 'Содом', image: '/1.jpg', link: '/index.html' },
		{ name: 'Неро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ванз', image: '/1.jpg', link: '/index.html' },
		{ name: 'Джабура', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фукуро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кумадори', image: '/1.jpg', link: '/index.html' },
		{ name: 'Каши', image: '/1.jpg', link: '/index.html' },
		{ name: 'Оймо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кервиль', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бас', image: '/1.jpg', link: '/index.html' },
		{ name: 'Принцесса', image: '/1.jpg', link: '/index.html' },
		{ name: 'Клевер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Спандайн', image: '/1.jpg', link: '/index.html' },
		{ name: 'Саул', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ольвия', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сакадзуки', image: '/1.jpg', link: '/index.html' },
	],
	group3: [
		{ name: 'Онигумо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ямакадзи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Доберман', image: '/1.jpg', link: '/index.html' },
		{ name: 'Момонга', image: '/1.jpg', link: '/index.html' },
		{ name: 'Стробери', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Аттатян', image: '/1.jpg', link: '/index.html' },
		{ name: 'Перона', image: '/1.jpg', link: '/index.html' },
		{ name: 'Абсалом', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хогбак', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бухитяк', image: '/1.jpg', link: '/index.html' },
		{ name: 'Синдри', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мокдональд', image: '/1.jpg', link: '/index.html' },
		{ name: 'Рюма', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кумаси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мория', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лола', image: '/1.jpg', link: '/index.html' },
		{ name: 'Орз', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дюваль', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мотобаро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шалулия', image: '/1.jpg', link: '/index.html' },
		{ name: 'Росвард', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сэнтомару', image: '/1.jpg', link: '/index.html' },
		{ name: 'Барт', image: '/1.jpg', link: '/index.html' },
		{ name: 'Арудж', image: '/1.jpg', link: '/index.html' },
		{ name: 'Апу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дрейк', image: '/1.jpg', link: '/index.html' },
		{ name: 'Капоне', image: '/1.jpg', link: '/index.html' },
		{ name: 'Киллер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хокинс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шакуяку', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кид', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пенгвин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бонни', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бепо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ло', image: '/1.jpg', link: '/index.html' },
		{ name: 'Чарлос', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хит', image: '/1.jpg', link: '/index.html' },
		{ name: 'Борсалино', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пацифиста', image: '/1.jpg', link: '/index.html' },
		{ name: 'Нён', image: '/1.jpg', link: '/index.html' },
		{ name: 'Свит Пи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Афеландра', image: '/1.jpg', link: '/index.html' },
		{ name: 'Маргарет', image: '/1.jpg', link: '/index.html' },
		{ name: 'Саломея', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сандерсония', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хэнкок', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бакура', image: '/1.jpg', link: '/index.html' },
		{ name: 'Юда', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тайгер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тибани', image: '/1.jpg', link: '/index.html' },
		{ name: 'Харедас', image: '/1.jpg', link: '/index.html' },
		{ name: 'Минотавр', image: '/1.jpg', link: '/index.html' },
		{ name: 'Магеллан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сади', image: '/1.jpg', link: '/index.html' },
		{ name: 'Инадзума', image: '/1.jpg', link: '/index.html' },
		{ name: 'Иванков', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ширью', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кэролайн', image: '/1.jpg', link: '/index.html' },
		{ name: 'Руж', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сквард', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бастилия', image: '/1.jpg', link: '/index.html' },
		{ name: 'Далматин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Изо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Литл', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шот', image: '/1.jpg', link: '/index.html' },
		{ name: 'Вульф', image: '/1.jpg', link: '/index.html' },
		{ name: 'Писарро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Девон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дадан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Магра', image: '/1.jpg', link: '/index.html' },
		{ name: 'Догра', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сабо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шоколя', image: '/1.jpg', link: '/index.html' },
		{ name: 'Монблютен', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гицунэ', image: '/1.jpg', link: '/index.html' },
		{ name: 'Торуко', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дрип', image: '/1.jpg', link: '/index.html' },
		{ name: 'Блэк', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мандзяро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кокоа', image: '/1.jpg', link: '/index.html' },
		{ name: 'Карибу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Корибу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Альбион', image: '/1.jpg', link: '/index.html' },
	],
	group4: [
		{ name: 'Суруме', image: '/1.jpgchopper.jpg', link: 'characters/chopper.html' },
		{ name: 'Вандер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Вадацуми', image: '/1.jpg', link: '/index.html' },
		{ name: 'Анкоро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сора', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сейра', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кайрен', image: '/1.jpg', link: '/index.html' },
		{ name: 'Джонс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хирамера', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фукабоси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Рюбоси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Манбоси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сярли', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сплаш', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сплатер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Нептун', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ширахоши', image: '/1.jpg', link: '/index.html' },
		{ name: 'Аладин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Отохиме', image: '/1.jpg', link: '/index.html' },
		{ name: 'Коала', image: '/1.jpg', link: '/index.html' },
		{ name: 'Линлин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пудинг', image: '/1.jpg', link: '/index.html' },
		{ name: 'Нитро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Наполеон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тамаго', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пекомс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кинемон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мотя', image: '/1.jpg', link: '/index.html' },
		{ name: 'Синд', image: '/1.jpg', link: '/index.html' },
		{ name: 'Комбу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Моне', image: '/1.jpg', link: '/index.html' },
		{ name: 'Цезарь', image: '/1.jpg', link: '/index.html' },
		{ name: 'Смайли', image: '/1.jpg', link: '/index.html' },
		{ name: 'Верго', image: '/1.jpg', link: '/index.html' },
		{ name: 'Гладиус', image: '/1.jpg', link: '/index.html' },
		{ name: 'Детка 5', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сахарок', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лао Джи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Махвайс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Джора', image: '/1.jpg', link: '/index.html' },
		{ name: 'Момоноске', image: '/1.jpg', link: '/index.html' },
		{ name: 'Баффало', image: '/1.jpg', link: '/index.html' },
		{ name: 'Диаманте', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пика', image: '/1.jpg', link: '/index.html' },
		{ name: 'Требол', image: '/1.jpg', link: '/index.html' },
		{ name: 'Канджиро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Пинк', image: '/1.jpg', link: '/index.html' },
		{ name: 'Деллинджер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кирос', image: '/1.jpg', link: '/index.html' },
		{ name: 'Виола', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ребекка', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сай', image: '/1.jpg', link: '/index.html' },
		{ name: 'Цинцзяо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кавендиш', image: '/1.jpg', link: '/index.html' },
		{ name: 'Викка', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бартоломео', image: '/1.jpg', link: '/index.html' },
		{ name: 'Рику', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хак', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хайрудин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Идео', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кабу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Лео', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бобомба', image: '/1.jpg', link: '/index.html' },
		{ name: 'Биан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Скарлетт', image: '/1.jpg', link: '/index.html' },
		{ name: 'Фарул', image: '/1.jpg', link: '/index.html' },
		{ name: 'Хоминг', image: '/1.jpg', link: '/index.html' },
		{ name: 'Росинант', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кайдо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Тристан', image: '/1.jpg', link: '/index.html' },
	],
	group5: [
		{ name: 'Джек', image: '/1.jpgJeck.jpg', link: 'characters/Jeck.html' },
		{ name: 'Уибл', image: '/1.jpg', link: '/index.html' },
		{ name: 'Баккин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ванда', image: '/1.jpg', link: '/index.html' },
		{ name: 'Марковка', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бариет', image: '/1.jpg', link: '/index.html' },
		{ name: 'Педро', image: '/1.jpg', link: '/index.html' },
		{ name: 'Блэкбэк', image: '/1.jpg', link: '/index.html' },
		{ name: 'Мияги', image: '/1.jpg', link: '/index.html' },
		{ name: 'Инуараши', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сисилиан', image: '/1.jpg', link: '/index.html' },
		{ name: 'Нэкомамуши', image: '/1.jpg', link: '/index.html' },
		{ name: 'Райдзо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Шифон', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ёнджи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Рейджу', image: '/1.jpg', link: '/index.html' },
		{ name: 'Амандо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Дизель', image: '/1.jpg', link: '/index.html' },
		{ name: 'Зевс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Прометей', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ичиджи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Ниджи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Брюле', image: '/1.jpg', link: '/index.html' },
		{ name: 'Джадж', image: '/1.jpg', link: '/index.html' },
		{ name: 'Перосперо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Петз', image: '/1.jpg', link: '/index.html' },
		{ name: 'Крекер', image: '/1.jpg', link: '/index.html' },
		{ name: 'Баум', image: '/1.jpg', link: '/index.html' },
		{ name: 'Сора', image: '/1.jpg', link: '/index.html' },
		{ name: 'Смузи', image: '/1.jpg', link: '/index.html' },
		{ name: 'Зепо', image: '/1.jpg', link: '/index.html' },
		{ name: 'Штрейзен', image: '/1.jpg', link: '/index.html' },
		{ name: 'Стусси', image: '/1.jpg', link: '/index.html' },
		{ name: 'Морганс', image: '/1.jpg', link: '/index.html' },
		{ name: 'Катакури', image: '/1.jpg', link: '/index.html' },
		{ name: 'Райдин', image: '/1.jpg', link: '/index.html' },
		{ name: 'Герт', image: '/1.jpg', link: '/index.html' },
		{ name: 'Кармель', image: '/1.jpg', link: '/index.html' },
		{ name: 'Флампе', image: '/1.jpg', link: '/index.html' },
		{ name: 'Брауни', image: '/1.jpg', link: '/index.html' },
		{ name: 'Бетти', image: '/1.jpg', link: '/index.html' },
		{ name: 'Морли', image: '/1.jpg', link: '/index.html' },
		{ name: 'Линдберг', image: '/1.jpg', link: '/index.html' },
	],
};

// Функция для изменения отображаемой группы персонажей
function changeGroup(group) {
	var charactersContainer = document.getElementById('charactersContainer');
	charactersContainer.innerHTML = ''; // Очищаем контейнер перед добавлением новых карточек

	// Перебираем персонажей выбранной группы и формируем HTML
	charactersData[group].forEach(function(character) {
		var cardHtml = `
				<div class="col mb-4">
					<div class="card text-bg-dark shadow-sm bg-body-tertiary position-relative overflow-hidden">
							<img src="${character.image}" class="img-fluid object-fit-cover skake" style="height: 300px;" alt="...">
							<div class="shake card-img-overlay d-flex align-items-end">
								<a href="${character.link}"><p class="card-title card-black stretched-link text-danger-hover">${character.name}</p></a>
							</div>
						</div>
				</div>
		`;

	charactersContainer.innerHTML += cardHtml; // Добавляем каждую карточку в контейнер
});
}

// Изначально отображаем первую группу при загрузке страницы
changeGroup('group1');